//increasing ellipse count over time
//Leon Wolff
//This program draws an increasing amount of ellipses with random colors

int exp;
int i = 0;
float posY;
float posX;
float size;
float copy;
int counting;

void settings (){
 size(800,800); 
  smooth();
}

void setup(){
  background(0); 
}


void mouseClicked(){
 if (mouseButton == LEFT){
  noLoop();}
 if (mouseButton == RIGHT){
  loop();
 }
}

void draw(){
  noFill();
  stroke(0, 255, 0);
  strokeWeight(0.05);
  println(i);
  ellipseMode(CENTER);
  
  if (i > 1799){
   noLoop(); 
  }
  
  if (i < 1800){
   i++; 
  }
  fill(random(255),random(255),random(255), 15);
  if (i > 0){
    drawer1();
  }
  if (i > 200){
    drawer2();
  }
  if (i > 400){
   drawer3(); 
  }
  if (i > 600){
   drawer4(); 
  }
  if (i >800){
   drawer5(); 
  }
  if (i > 1000){
   drawer6(); 
  }
  if (i > 1200){
   drawer7(); 
  }
  if (i > 1400){
   drawer8(); 
  }
  if (i > 1600){
   drawer9(); 
  }
  if (i > 1800){
   drawer10(); 
  }
}

void drawer1(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 200), copy = this.size);
 
}

void drawer2(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 200), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 200), copy = this.size);
}

void drawer3(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
}

void drawer4(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
}

void drawer5(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
}

void drawer6(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
}

void drawer7(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
}

void drawer8(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
}

void drawer9(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
}

void drawer10(){
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
  ellipse (posX = random(10, width), posY = random(10, height), size = random(10, 400), copy = this.size);
}
